name: sunlight
description: Automatic event documentation with screenshots for Flutter applications.
version: 0.2.0
repository: https://github.com/viniciusaro/sunlight

environment:
  sdk: ^3.7.0

dependencies:
  http: ^1.3.0
  http_parser: ^4.0.0
  mutex: ^3.1.0

dev_dependencies:
  lints: ^5.0.0