name: sunlight_flutter
description: Automatic event documentation with screenshots for Flutter applications.
version: 0.1.0
repository: https://github.com/viniciusaro/sunlight

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.5
  screenshot: ^3.0.0
  sunlight: ^0.2.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0