name: sunlight_flutter
description: Automatic event documentation with screenshots for Flutter applications.
version: 0.1.0
repository: https://github.com/viniciusaro/sunlight
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.5
  screenshot: ^3.0.0
  
  sunlight:
    path: ../sunlight
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0